# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dell\Desktop\Novel\111.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NovelGet(object):
    def setupUi(self, NovelGet):
        NovelGet.setObjectName("NovelGet")
        NovelGet.resize(400, 136)
        self.start = QtWidgets.QPushButton(NovelGet)
        self.start.setGeometry(QtCore.QRect(140, 50, 121, 31))
        self.start.setAutoDefault(False)
        self.start.setDefault(False)
        self.start.setFlat(False)
        self.start.setObjectName("start")
        self.URLget = QtWidgets.QLineEdit(NovelGet)
        self.URLget.setGeometry(QtCore.QRect(30, 10, 351, 31))
        self.URLget.setAlignment(QtCore.Qt.AlignCenter)
        self.URLget.setObjectName("URLget")
        self.IprogressBar = QtWidgets.QProgressBar(NovelGet)
        self.IprogressBar.setGeometry(QtCore.QRect(30, 100, 371, 21))
        self.IprogressBar.setProperty("value", 0)
        self.IprogressBar.setObjectName("progressBar")

        self.retranslateUi(NovelGet)
        QtCore.QMetaObject.connectSlotsByName(NovelGet)

    def retranslateUi(self, NovelGet):
        _translate = QtCore.QCoreApplication.translate
        NovelGet.setWindowTitle(_translate("NovelGet", "Novel Get"))
        self.start.setText(_translate("NovelGet", "开始生成"))
        self.URLget.setText(_translate("NovelGet", "请输入小说章节目录网址"))
